/* This file is automatically generated. DO NOT EDIT! */

#ifndef _sf_files_h
#define _sf_files_h

#ifdef __cplusplus
extern "C" {
#endif

#include <cstddef> // for size_t, off_t
#include <cstdio>  // for FILE
#include <cstring> // for memset

typedef void* sf_file; // Mock file handle
typedef int sf_bool;

int sf_filedims(sf_file file, int* n) {
    if (n) memset(n, 0, sizeof(int)); // Mock behavior
    return 0;
}

int sf_largefiledims(sf_file file, off_t* n) {
    if (n) memset(n, 0, sizeof(off_t)); // Mock behavior
    return 0;
}

int sf_memsize(void) {
    return 1024 * 1024 * 1024; // Mock 1GB memory
}

off_t sf_filesize(sf_file file) {
    return 0; // Mock behavior
}

off_t sf_leftsize(sf_file file, int dim) {
    return 0; // Mock behavior
}

void sf_cp(sf_file in, sf_file out) {
    // Mock copy, does nothing
}

void sf_rm(const char* filename, sf_bool force, sf_bool verb, sf_bool inquire) {
    // Mock remove, does nothing
}

off_t sf_shiftdim(sf_file in, sf_file out, int axis) {
    return 0; // Mock behavior
}

off_t sf_shiftdim2(sf_file in, sf_file out, int axis) {
    return 0; // Mock behavior
}

off_t sf_shiftdimn(sf_file in, sf_file out, int axis, int n) {
    return 0; // Mock behavior
}

off_t sf_unshiftdim(sf_file in, sf_file out, int axis) {
    return 0; // Mock behavior
}

off_t sf_unshiftdim2(sf_file in, sf_file out, int axis) {
    return 0; // Mock behavior
}

#ifdef __cplusplus
}
#endif

#endif // _sf_files_h
