import sys, os, glob
sys.path.append('../../../framework')

from SCons.Script import Dir
# api_cpp_dir = Dir('#/api/mdio').abspath
api_cpp_dir = Dir('#/api/c/mdio').abspath
if api_cpp_dir not in sys.path:
    sys.path.insert(0, api_cpp_dir)

import bldutil
import sys
from SCons.Script import Import, Environment, Dir

# Ensure necessary imports and environment setup
try:
    Import('env root libdir incdir')
    env = env.Clone()
except:
    env = bldutil.Debug()
    root = None
    SConscript('../SConstruct')


# Add include and library paths
env.Prepend(
    CPPPATH=['../../../include'],
    LIBPATH=['../../../lib'] 
)


# --- MDIO Optional Dependency Support ---
import setup_mdio
from setup_mdio import setup_mdio

if int(env.get('MDIO', 0)):  # Check if MDIO is enabled
    mdio_dir = setup_mdio(env, root)

# Define source files
mdio_test_src = "mdio_file_test.c"
sf_file_src = "mdio_file.cc"

env.Replace(LINK="g++")

# Compile C and C++ sources
mdio_test_obj = env.Object(mdio_test_src)
sf_file_obj = env.Object(sf_file_src)

# Link them into the mdio_test executable
mdio_test_exe = env.Program("mdio_file_test", [mdio_test_obj, sf_file_obj])

# Set default build target
Default(mdio_test_exe)


sf_file_obj = env.Object(sf_file_src)
print(f"Compiling: {sf_file_src} -> {sf_file_obj}")
