import os, sys, string, glob
sys.path.append('../../framework')
sys.path.append('../../api/c++')
from SCons.Script import Dir
api_cpp_dir = Dir('#/api/c++').abspath
if api_cpp_dir not in sys.path:
    sys.path.insert(0, api_cpp_dir)
# from setup_mdio import setup_mdio
import bldutil
import setup_mdio  # Import the module directly
from setup_mdio import setup_mdio  # Then import the functio

progs = '''
klipp
'''

try:  # distributed version
    Import('env root bindir pkgdir')
    env = env.Clone()
except: # local version
    env = bldutil.Debug()
    root = None
    SConscript('../../api/c++/SConstruct')

env.Append(CPPPATH=['../../include'],
           LIBPATH=['../../lib'],
           LIBS=['rsf++', 'rsf', 'tirpc', 'nsl'])

auxFlags = [
    "-w",
    "-DMAX_NUM_SLICES=32",
    "-DNO_BLAS",
    "-DFS_HAS_RPC=False"
]
for flag in auxFlags:
    env.Append(CXXFLAGS=f" {flag}")

if int(env.get('MDIO', 0)):
    print("MDIO support enabled. Configuring MDIO dependency via API module.")
    # env = setup_mdio(env, root)
    setup_mdio(env, root)
    print("###########After setting up MDIO###########")
    print(f"CPPPATH: {env.get('CPPPATH')}")
    print(f"LIBPATH: {env.get('LIBPATH')}")
    print(f"LINKFLAGS: {env.get('LINKFLAGS')}")
else:
    print("WARNING: MDIO support is disabled. Compiling without MDIO support.")
    env.Append(CCFLAGS=['-DNO_MDIO'])

mains = Split(progs)
for prog in mains:
    sources = [prog + '.cc']
    prog_target = env.Program(prog, sources)
    if root:
        env.Install(bindir, prog_target)

######################################################################
# SELF-DOCUMENTATION
######################################################################
if root:
    user = os.path.basename(os.getcwd())
    main_doc = 'sf%s.py' % user
    
    docs = [env.Doc(prog, prog + '.cc', lang='c++') for prog in Split(progs)]
    env.Depends(docs, '#/framework/rsf/doc.py')
    doc = env.RSF_Docmerge(main_doc, docs)
    env.Install(pkgdir, doc)
##################################################################### 