import sys, os, glob
sys.path.append('../../framework')
# Add the directory containing this SConstruct file to the Python path
from SCons.Script import Dir
api_cpp_dir = Dir('#/api/c++').abspath
if api_cpp_dir not in sys.path:
    sys.path.insert(0, api_cpp_dir)

import bldutil
import setup_mdio  # Import the module directly
from setup_mdio import setup_mdio  # Then import the function

sources = Split('rsf cub')

try:  # distribution version
    Import('env root libdir incdir')
    env = env.Clone()
except:  # local version
    env = bldutil.Debug()
    root = None
    SConscript('../c/SConstruct')

dynpre = env.get('DYNLIB', '')

env.Prepend(CPPPATH=['../../include'],
            LIBPATH=['../../lib'],
            LIBS=[dynpre + 'rsf'])

# --- MDIO Optional Dependency Support ---
if int(env.get('MDIO', 0)):
    mdio_dir = setup_mdio(env)
# --- End MDIO support ---

dynlib = ('-static-intel' not in env.get('LINKFLAGS', ''))
dlibs = ['drsf'] + env.get('LIBS', [])

if 'c++' in env.get('API', []):
    ccfiles = [x + '.cc' for x in sources]
    hhfiles = [x + '.hh' for x in sources]
    dobjects = list(map(env.SharedObject, ccfiles))

    lib = env.StaticLibrary('rsf++', ccfiles, CCFLAGS='')
    env.Install('../../lib', lib)
    env.Install('../../include', hhfiles)

    if root:
        env.Install(libdir, lib)
        env.Install(incdir, hhfiles)

    if dynlib:
        dlib = env.SharedLibrary('rsf++', dobjects, SHLIBPREFIX='libd', LIBS=dlibs)
        env.Install('../../lib', dlib)

        if root:
            install = env.Install(libdir, dlib)

            if dynpre and env['PLATFORM'] == 'darwin':
                env.AddPostAction(
                    install,
                    '%s -change build/api/c/libdrsf.dylib '
                    '%s/libdrsf.dylib %s' % (
                        WhereIs('install_name_tool'), libdir, install[0]
                    )
                )

    for file in ['getpar', 'file']:
        test = 'Test' + file + '.cc'
        env.Program(file, [test, lib], PROGSUFFIX='.x', PROGPREFIX='Test')